language: bash
sudo: required

git:
  depth: 1

jobs:
  include:
    - os: linux
      dist: focal # Ubuntu 20.04
      script: ${TRAVIS_BUILD_DIR}/setup.sh -a

before_install:
  - sudo apt-get -y install unattended-upgrades

before_script:
  # docker already installed, disable it
  - sed -i "/install docker-ce/d" ${TRAVIS_BUILD_DIR}/setup.sh
  - sudo systemctl stop docker.socket
  - sudo systemctl stop docker
  # flush and delete DOCKER-USER chain
  - sudo iptables -F DOCKER-USER
  - sudo iptables -X DOCKER-USER
  # enable ipv6
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
