language: bash
sudo: required

git:
  depth: 1

jobs:
  include:
    - os: linux
      dist: focal # Ubuntu 20.04
      script:
        - shellcheck ${TRAVIS_BUILD_DIR}/*.sh
        - ${TRAVIS_BUILD_DIR}/setup.sh -a

before_install:
  - sudo apt-get -y install unattended-upgrades

before_script:
  # docker already installed, disable it
  - sed -i "/install docker-ce/d" ${TRAVIS_BUILD_DIR}/setup.sh
  - sudo systemctl stop docker.socket
  - sudo systemctl stop docker
  # clear iptables rules
  - sudo iptables -P INPUT ACCEPT
  - sudo iptables -P FORWARD ACCEPT
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -t nat -F
  - sudo iptables -t mangle -F
  - sudo iptables -F
  - sudo iptables -X
  # clear ip6tables rules
  - sudo ip6tables -P INPUT ACCEPT
  - sudo ip6tables -P FORWARD ACCEPT
  - sudo ip6tables -P OUTPUT ACCEPT
  - sudo ip6tables -t nat -F
  - sudo ip6tables -t mangle -F
  - sudo ip6tables -F
  - sudo ip6tables -X
  # enable ipv6
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
