version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Asia/Singapore'
      WEBPASSWORD: '123456'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      # Web Interface
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.merlion.bibilcorp.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # DNS 53/UDP
      - "traefik.udp.routers.dns.entrypoints=dns"
      - "traefik.udp.routers.dns.service=pihole"
      - "traefik.udp.services.pihole.loadbalancer.server.port=53"
      # DNS 53/TCP
      - "traefik.tcp.routers.dns-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.dns-tcp.entrypoints=dns-tcp"
      - "traefik.tcp.routers.dns-tcp.service=pihole"
      # DNS-over-TLS
      - "traefik.tcp.routers.dns-over-tls.rule=HostSNI(`pihole.merlion.bibilcorp.com`)"
      - "traefik.tcp.routers.dns-over-tls.entrypoints=dns-over-tls"
      - "traefik.tcp.routers.dns-over-tls.tls.certresolver=le"
      - "traefik.tcp.routers.dns-over-tls.service=pihole"
      # Traffic from TLS and non-TLS routers
      - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
    networks:
     - web
networks:
  web:
    external: true