version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls.certResolver=le"
      - "--certificatesresolvers.le.acme.email=yannick.bilcot@laposte.net"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--entrypoints.dns.address=:53/udp"
      - "--entrypoints.dns-tcp.address=:53"
      - "--entrypoints.dns-over-tls.address=:853"
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "53:53"
      - "53:53/udp"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './acme.json:/acme.json'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.merlion.bibilcorp.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$2y$05$FKruLtzy/Bq.qvowsC3ntuP3oOgnK8ZH1n3k/Jm/4721LBNOoH5Ua"
    networks:
      - web
networks:
  web:
    external: true